### ISSUE TITLE
Getting error "nonetype' object is not subscriptable"

### ISSUE THREAD

**Issue by DKnight54** [Talmendo/blip2-for-sd#1]
Not sure if you've experience this in the latest revision of the code, but when trying to run it, I'm getting a constant stream of "nonetype' object is not subscriptable" error, and it's generating empty caption files.
![image](https://github.com/Talmendo/blip2-for-sd/assets/126916963/8e1ec80f-c6b9-4e21-89b0-b435f7762f57)

Unfortunately, while I learned enough to figure out setting up the script in VENV, I can't figure out where the issue is.

**Comment by Talmendo** [comment]
Hey, there's been some fixes in the newest version, I'd definitely recommend updating. You'll have to install some new dependencies with `pip install -r requirements.txt`
If it still doesn't work afterwards, I'd double check if your file setup is correct. It works similarly to kohya, if you're familiar with that. You point to a root directory that only contains other folders. Each folders name is the base prompt for the images inside.
Alternatively, you can try the new python notebook I've included.

**Comment by DKnight54** [comment]
Whoa! that was quick! Tested it out and it's working fine on my setup now!
