### ISSUE TITLE
CaptionProcessor.gen() got an unexpected keyword argument 'do_sample'

### ISSUE THREAD

**Issue by yingguanchana** [Talmendo/blip2-for-sd#2]
I have installed all the dependencies listed in requirements.txt and ensured that the folder is named 'photo of a woman'. However, when processing the images, I encountered the message 'Found 729 files for prompt "photo of a beautiful Asian woman" 0%|▏ | 2/729 [00:00<01:32, 7.85it/s] CaptionProcessor.gen() got an unexpected keyword argument 'do_sample.' In the end, all the generated txt files are empty.

**Comment by OlKasmir** [comment]
I had the same problem. I fixed it by changing the code of the caption_processor.py
Replace those two functions and it should work.

```
  def gen_from_config(self, inputs, config):
    return self.gen(
      inputs,
      max_length=config["max_length"],
      min_length=config["min_length"],
      top_k=config["top_k"],
      top_p=config["top_p"],
      num_beams=config["num_beams"],
      repetition_penalty=config["repetition_penalty"],
      no_repeat_ngram_size=config["max_repititions"],
      do_sample=config["do_sample"],
    )

  def gen(self, inputs, max_length=10, min_length=0, top_k=30, top_p=0.92, num_beams=4, repetition_penalty=1.5, no_repeat_ngram_size=2, do_sample=False):
    return self.model.generate(
      **inputs,
      # max_new_tokens=25,                        # Number of tokens to generate
      max_length=max_length,                      # Maximum length of the sequence to be generated, mutually exclusive with max_new_tokens
      num_beams=num_beams,                        # Number of beams to use for beam search
      num_return_sequences=1,                     # Number of captions to generate
      early_stopping=True,                        # Stop when no new tokens are generated
      repetition_penalty=repetition_penalty,      # Penalize repeated words
      no_repeat_ngram_size=no_repeat_ngram_size,  # Number of words that can be repeated
      do_sample=do_sample,                        # Introduce randomness to captions
      # temperature=0.9,                          # Measure of randomness 0-1, 0 means no randomness
      top_k=top_k,                                # Number of highest probability tokens to keep, 0 means no filtering
      top_p=top_p,                                # Probability threshold, 0 means no filtering
      min_length=min_length,                      # Minimum length of the sequence to be generated
    )
```

In case the original developer sees this, did you also get really bad results from your captions? Most of them seem like hallucinations or completely random. Especially for those where you mentioned multiple choice. I've created a python gui to upload a single image, changing parameters and for being able to ask questions but i couldn't get it to generate good answers. I was pretty disappointed. But it's still useful for basic setup but for most of the captions i had to change almost everything.

**Comment by Talmendo** [comment]
This issue has been fixed in the most recent update!

@OlKasmir Have you been using the blip 2.7b model? That one seems to be quite weak especially with those multiple choice questions. I think you can get it to work, but you would need to tweak the parameters a bit.
I'd recommend `Salesforce/blip2-opt-6.7b-coco` for the model, that one works well. If VRAM is an issue there and you're on Linux there's now also an option to use 4bit quantization by installing bitsandbytes. Just pass `use_4bit=True` to the `load_model` method. That reduced VRAM requirements to about 10GB.

**Comment by OlKasmir** [comment]
@Talmendo I was using load_model("Salesforce/blip2-opt-6.7b-coco"). Was > 30GB to download. But it uses only about 8 GB VRAM on my windows system. That seemed a bit weird. It took about 150 seconds per Image. I've let it run over night on 140 images. 95% of captions said candid for example when it obviously wasn't. Also 90% of the time it said from the side, when it was from front. Maybe I messed something up.

For reference. Those are the captions created on my PC from your two example pictures:
`candid, photo of a woman, with brunette shoulder length hair, wearing a hat and sweater and  boots, sitting on a rock,  full body shot, a woman sitting on a rock in front of a waterfall, natural lighting`
`candid, photo of a woman, with brown shoulder length hair, wearing a white t-shirt, posing for a picture, full body shot, a woman in a white t-shirt against a blue wall, soft lighting`
